# Generated by Django 5.2.8 on 2025-12-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Элемент меню',
                'verbose_name_plural': 'Элементы меню',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('url', models.CharField(max_length=255, null=True, verbose_name='Ссылка на страницу')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='PagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Права ролей на странице',
                'verbose_name_plural': 'Права ролей на странице',
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Иконка')),
            ],
            options={
                'ordering': ('order_num',),
            },
        ),
    ]
