# Generated by Django 5.2.8 on 2025-12-04 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='role_can_view',
            field=models.ManyToManyField(blank=True, related_name='roles_can_view_top_level_menu', to='user.role', verbose_name='Кто видит страницу в меню'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Указать, если нет подменю', null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.page'),
        ),
        migrations.AddField(
            model_name='pagepermission',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='shared.page'),
        ),
        migrations.AddField(
            model_name='pagepermission',
            name='permissions',
            field=models.ManyToManyField(to='user.permission'),
        ),
        migrations.AddField(
            model_name='pagepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.role'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='shared.menuitem'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.page'),
        ),
        migrations.AddField(
            model_name='submenuitem',
            name='role_can_view',
            field=models.ManyToManyField(blank=True, related_name='roles_can_view_sub_level_menu', to='user.role', verbose_name='Кто видит страницу в меню'),
        ),
    ]
