# Generated by Django 5.2.8 on 2026-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tg_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='TG ID'),
        ),
    ]
