# Generated by Django 5.2.8 on 2026-01-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='PDF отчёт'),
        ),
    ]
