# Generated by Django 5.2.8 on 2026-02-09 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_pdf_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fio', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Учредитель компании',
                'verbose_name_plural': 'Учредители компаний',
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fio', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('inn', models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН')),
                ('passport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер паспорта')),
                ('registration', models.TextField(blank=True, null=True, verbose_name='Прописка')),
            ],
            options={
                'verbose_name': 'Руководитель компании',
                'verbose_name_plural': 'Руководители компаний',
            },
        ),
        migrations.CreateModel(
            name='CompanyHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.head')),
            ],
            options={
                'verbose_name': 'Руководитель конкретной компании',
                'verbose_name_plural': 'Руководители конкретной компаний',
            },
        ),
    ]
