# Generated by Django 5.2.8 on 2026-02-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_founder_head_companyhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhead',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='company.company'),
        ),
    ]
