# Generated by Django 5.2.8 on 2026-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_companyhead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyhead',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyhead',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
