# Generated by Django 5.2.8 on 2026-02-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companyhead_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='director_name',
        ),
    ]
