# Generated by Django 5.2.8 on 2026-03-06 13:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_company_director_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founder',
            name='fio',
        ),
        migrations.AddField(
            model_name='founder',
            name='fio_company',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО\\Название компании'),
        ),
        migrations.AddField(
            model_name='founder',
            name='inn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН'),
        ),
        migrations.CreateModel(
            name='CompanyFounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='company.company')),
                ('founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.founder')),
            ],
            options={
                'verbose_name': 'Учредитель конкретной компании',
                'verbose_name_plural': 'Учредители конкретной компаний',
            },
        ),
    ]
