# Generated by Django 5.2.8 on 2025-12-04 12:53

import apps.document.models.version
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тега документа')),
            ],
            options={
                'verbose_name': 'Тег документа',
                'verbose_name_plural': 'Теги документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название типа документа')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.document.models.version.document_upload_path, verbose_name='Файл')),
                ('on_approval', models.BooleanField(default=True, verbose_name='На утверждении')),
                ('approved', models.BooleanField(default=False, verbose_name='Утвержден')),
                ('rejected', models.BooleanField(default=False, verbose_name='Отклонен')),
                ('missing', models.BooleanField(default=False, verbose_name='Отсутствует')),
                ('upload_date', models.DateField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('valid_from', models.DateField(blank=True, help_text='Дата начала действия версии', null=True, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, help_text='Дата окончания действия версии', null=True, verbose_name='Действует до')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Дата проверки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('rejection_reason', models.TextField(blank=True, help_text='Заполняется при отклонении версии', verbose_name='Причина отказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущая версия')),
            ],
            options={
                'verbose_name': 'Версия документа',
                'verbose_name_plural': 'Версии документов',
                'ordering': ['document', '-version'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название документа')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_date'],
            },
        ),
    ]
