# Generated by Django 5.2.8 on 2025-12-04 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='aliases',
            field=models.ManyToManyField(blank=True, to='document.documenttag', verbose_name='Алиасы (теги)'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='applicable_company_types',
            field=models.ManyToManyField(blank=True, to='company.companytype', verbose_name='Применимые типы компаний'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.documenttype', verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='document.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_document_versions', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверил'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_document_versions', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['company', 'document_type'], name='document_do_company_7faaa2_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_date'], name='document_do_created_212c87_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'is_current', 'is_active'], name='document_do_documen_e2f693_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document', 'approved', 'valid_until'], name='document_do_documen_3efc19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version')},
        ),
    ]
