# Generated by Django 5.2.8 on 2025-12-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='slug',
            field=models.CharField(max_length=255, null=True, verbose_name='Код типа документа'),
        ),
    ]
