# Generated by Django 5.2.8 on 2026-01-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='slug',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Код типа документа'),
        ),
    ]
