# Generated by Django 5.2.8 on 2026-02-09 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companyhead_end_date_and_more'),
        ('document', '0007_alter_documenttype_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.head'),
        ),
    ]
