# Generated by Django 5.2.8 on 2026-02-09 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_companyhead_end_date_and_more'),
        ('document', '0008_documentversion_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companyhead'),
        ),
    ]
